### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by afdezmor** [creewick/MontereyRainmeter#104]
I am doing a translation into Spanish but I don't know how to edit the names of the months or the names of the days. 
![image](https://github.com/creewick/MontereyRainmeter/assets/46401084/23c643a5-3735-4f77-bdc0-8dbd51bae1f0)
![image](https://github.com/creewick/MontereyRainmeter/assets/46401084/20030aca-aa9f-4558-9e8b-8d33350ca01e)

**Comment by CodeBreaker518** [comment]
You don't hardcode edit the names, I already translate it for spanish for myself and I think just making a good config (make sure, you also include the spanish language config in `@Resources/Scripts/Contexts/Languages.inc` ).
This way the weather's API and the other ones recognize the actual language selected and return the results in spanish in this case.

![image](https://github.com/creewick/MontereyRainmeter/assets/49607711/cb388374-66b3-4578-ae74-b246c12d3f1c)

**Comment by afdezmor** [comment]
Thanks, thank that worked for me.
