### ISSUE TITLE
Blur mode is not transparent on my pc

### ISSUE THREAD

**Issue by sq4567** [creewick/MontereyRainmeter#108]
![스크린샷 2024-08-14 122933](https://github.com/user-attachments/assets/ac6fba31-4689-45a5-81a6-c08d166cdc32)

**Comment by creewick** [comment]
Check that Low Power mode is not enabled in your system and that you have transparency effect on other windows, then restart Rainmeter.

If that didn't help, consider switching to [uWidgets](https://github.com/creewick/uWidgets)
