### ISSUE TITLE
Can't update to V 1.0 

### ISSUE THREAD

**Issue by adrieniisc** [creewick/MontereyRainmeter#31]
Hey brother !
First of all your project is a killer !!
So I installed the 0.7.rmskin but now I downloaded the 1.0 files, replaced them in the directory and nothing seems to have changed :/ 
Don't know if it's my fault, my bad if it is !

Btw the weather widget is displaying error 401 which I know what means but nothing happened after a while, knowing I got my active api key from OpenWeather (I can't change city name in the widget too)

Thanks a lot ;)

**Comment by creewick** [comment]
Hi, thanks for reaching out!
Glad you liked the project! ;)

Actually, there's no public release of v1.0 yet. The main branch is currently in WIP state, sorry for inconvenience
I'm planning to finish it in a week or two, you can check the progress on [the Roadmap page](https://github.com/users/creewick/projects/1)

About the weather widget - have you created an OpenWeather account and pasted your API key into widget settings?
If so, how long ago have you created it? 

You also said, that you can't change city name - how does it look like? Like the setting not saved? or like it saved, but there's error 401 for any entered city? Any screenshots or GIF of the occurring problem would help

**Comment by creewick** [comment]
Hi! Version 1.0 is available now ;)

**Comment by adrieniisc** [comment]
Hi man!

So I created the account like 2 hours ago and pasted the key in the
sertings without problem, but as soon as I hit save the error appears and I
can’t do anything.

And when I try to change the name, whether it’s clicking outside the
widget, inside, pressing enter or save, the name turns instantly back to
Yakateringburg. Doesn’t even display half of a second what I entered.
