### ISSUE TITLE
Weather Widget not letting me change my location

### ISSUE THREAD

**Issue by NintendoPSproG2** [creewick/MontereyRainmeter#33]
It's not letting me change my location in the Weather widget.

**Comment by creewick** [comment]
Try to update to 1.0 version. It may solve your problem. 
If not, you'll see one of the following error screen (click ⚠️ sign to see it)
- City is not found
   In that case, you'll be offered to fill your location's coordinates manually.
- Request limit exceeded
   You'll see this, if you didn't created a personal API key. You'll be offered to create one (it's free)
- Wrong API key
   You'll see this, if you just created a personal API key and it's not yet ready to use. In that case, you just need to wait a several hours and try again

If the problem still persists, please let me know

**Comment by creewick** [comment]
I've sent you an e-mail via feedback

This way should help for you:
- Visit https://www.latlong.net/
- Enter your city's name, click Find
- Copy your city's Latitude and Longitude values from the site
- Open `Rainmeter\Skins\Monterey\@Resources\Variables\Weather.inc` with any text editor
(you can find Skins folder by `Ctrl+click` any widget and selecting `Rainmeters - Skins - Open folder`)
- Paste your values after `Latitude=` and` Longitude=` respectively, then Save

Let me know if that helped so I could close the issue

**Comment by NintendoPSproG2** [comment]
It did! Thanks (sorry for answering late)
