### ISSUE TITLE
No support for all cities in Weather Widget

### ISSUE THREAD

**Issue by jaumedameson** [creewick/MontereyRainmeter#40]
Hi! 

I've been using these skins for a while now and I love them, but I have a little issue with the weather widget. It seems that it's not compatible with all cities. For exemple, no city in Catalonia (Spain) works. When I try to write one, the name is deleted and the previous one is loaded.

Is there any fix?

PS: Everything else works really fine, you did a great job.

Edit: I solved the issue editing the values in Weather.inc manually.

**Comment by clientsocial** [comment]
I had the same issue, but I figured it out. You have to type the city name, then press enter for it to accept it. Then hit save. I realized it's treating the text box like a form and you have to submit before you can store the settings.

**Comment by modtang** [comment]
I'm having the same issue. I'm trying to add my city (Wollongong, AU) but it just won't let me. Keeps reverting to the last city I put in there (Sydney). Any idea as to why?

**Comment by honsontran** [comment]
@jaumedameson can you show us how you modified `Weather.inc`?

**Comment by Celarye** [comment]
@honsontran just look for the coordinates of your city on https://openweathermap.org/ and then put those in your `C:\Users\<User>\Documents\Rainmeter\Skins\Monterey@Resources\Variables\Weather.inc` file. Also don't forget to manually change the name of the Location.

**Comment by creewick** [comment]
Please update to v1.0.1
If the problem still persists, re-open the issue
