### ISSUE TITLE
My OpenWeatherMap API Key isn`t working

### ISSUE THREAD

**Issue by FuchsBene** [creewick/MontereyRainmeter#54]
I created many new API keys but none of them worked. I'm sure they're enabled, but I get an error every time that the key isn't valid.

**Comment by NiklasWyld** [comment]
Have you checked that your api key is valid and working? You can check it with this link, if you are not getting a valid response or a response with an error, something with your key isn't right.

Link: http://api.openweathermap.org/data/2.5/weather?q=Straubing,DE&appid=API_KEY&units=metric
Replace API_KEY trough your api key.

**Comment by honsontran** [comment]
@NiklasWyld My API key is confirmed working, but when I take this same key to pop into the settings menu of the weather widget, it just says the key is not valid. What gives?

**Comment by FuchsBene** [comment]
I have tested my key and got valid information returned.

**Comment by Legend0804** [comment]
I'm having the same issue

**Comment by jonassvidras** [comment]
Maybe default, I assume PAID **openweathermap.org** account can use API requests using `onecall`, but when the request limit ends, and I replace the default API Key with mine, the free version accounts can use `weather?` requests?

**Comment by HanDzu** [comment]
Having the same issue, kinda annoying but not a big deal..

**Comment by creewick** [comment]
That really became a problem when this skin pack became so popular x)

I'll try to fix it in the .NET version. I hope, there will be no need to replace the API key each time it reaches the limit

**Comment by WonTheDev** [comment]
> That really became a problem when this skin pack became so popular x)
> 
> I'll try to fix it in the .NET version. I hope, there will be no need to replace the API key each time it reaches the limit

Hi, have you solved this problem? I really like yours. I hope it works well!

**Comment by creewick** [comment]
Please update to v.1.0.1
If the problem still persists, re-open the issue

**Comment by WonTheDev** [comment]
> Please update to v.1.0.1 If the problem still persists, re-open the issue

That is awesome! thank you for your effort!
