### ISSUE TITLE
[BUG?] City not available in weather widget

### ISSUE THREAD

**Issue by Celarye** [creewick/MontereyRainmeter#55]
I'm currently using the weather widget with my own API Key and it works for cities like 'London' or 'Ghent'. But when I try to change it to my local city 'Beervelde' it just switches back to the previously working city.

This link shows that openweathermap indeed has info for 'Beervelde'.
http://api.openweathermap.org/data/2.5/weather?q=Beervelde,BE&appid=6dd39489554c1ca221409f58867cc698&units=metric

Is this a bug or am I doing something wrong?

**Comment by Celarye** [comment]
Same issue as mentioned in #40.

**Comment by Legend0804** [comment]
I've found the solution.
Go to https://openweathermap.org/
Search your city from **THE SEARCH BOX IN TOP LEFT CORNER** 
The one which says "Weather in your city"
Not the one in the center of page saying "Search city"
It would provide you with coordinates of your place
Now minimize the window and navigate to : "C:\Users\Documents\Rainmeter\Skins\Monterey\@Resources\Variables\Weather.inc"
Open that variables file and manually put your city name and coordinates and save the file
Now refresh the skin
It would work

**Comment by Celarye** [comment]
This is indeed a way to fix this issue.

Thank you for your help!
