### ISSUE TITLE
Wrong API key

### ISSUE THREAD

**Issue by kevinmadson** [creewick/MontereyRainmeter#84]
I did exactly the steps to create a personal API from that link:

https://github.com/creewick/MontereyRainmeter/wiki/Get-weather-API-key

it is active, I put it in the widget but it does not work, what can I be doing wrong?

![image](https://github.com/creewick/MontereyRainmeter/assets/36973034/5b459e02-1265-443e-bdfd-65a441dd8e7f)
![NfeyWY2emV](https://github.com/creewick/MontereyRainmeter/assets/36973034/d64bcd3e-d72a-4a53-9060-6874b74234bb)

**Comment by creewick** [comment]
Please download the newest release of MontereyRainmeter.
https://github.com/creewick/MontereyRainmeter/releases/tag/v1.0.1
There's no need to create an API key anymore

**Comment by kevinmadson** [comment]
thanks for the support so fast, that worked! <3
