### ISSUE TITLE
Blur appearance shows black square background instead

### ISSUE THREAD

**Issue by PabloAlexis611** [creewick/MontereyRainmeter#90]
OS: Windows 11

**Comment by Dinoca35** [comment]
Go to Setings
Then go to Customization tab
Go to Colors tab
And enable the Transparency Effects option

**Comment by PabloAlexis611** [comment]
I did the above and the issue persisted.

At some point, it started working. I'm unsure of what might've caused it 🤷🏼‍♂️ 

Closing issue! (:
